version: 2

sources:
  - name: my_project
    database: TEST_DATABASE  
    schema: raw  
    tables:
      - name: nation
      - name: customer
      - name: region
      - name: orders

  - name: stripe
    tables:
      - name: payments